In [1]:
# pip install geopy geopandas shapely

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import prepare_data

In [4]:
data = prepare_data.open_and_clean_all(
    "data/raw/clalit/diaries.csv",
    "data/raw/maccabi/maccabi_full_data_with_appointments.json",
)

In [5]:
data.head(5)

,timestamp,available_date,kupah,profession,doctor_name,address,days_diff,city
0,2026-07-30 13:01:20,2026-08-11,clalit,אורתופדיה,"ד""ר הלר אייל","דרך משה דיין 147, תל אביב יפו",12.0,תל אביב יפו
1,2026-07-30 13:01:20,2026-08-14,clalit,אורתופדיה,"ד""ר צרפתי ירון","אליהו ברלין 13, תל אביב יפו",15.0,תל אביב יפו
2,2026-07-30 13:01:20,2026-08-16,clalit,אורתופדיה,"ד""ר אשכול זאב","אבן גבירול 124, תל אביב יפו",17.0,תל אביב יפו
3,2026-07-30 13:01:20,2026-08-16,clalit,אורתופדיה,"ד""ר סודיה דן","שדרות ישראל גורי 39, תל אביב יפו",17.0,תל אביב יפו
4,2026-07-30 13:01:20,2026-08-17,clalit,אורתופדיה,"ד""ר לשינר ויאצ'סלב","שדרות יד לבנים 35, תל אביב יפו",18.0,תל אביב יפו

In [6]:
data.to_csv("data/clean/maccabi.csv", index=False)
data[data["kupah"] == "maccabi"].to_csv("data/clean/maccabi.csv", index=False)
data[data["kupah"] == "clalit"].to_csv("data/clean/clalit.csv", index=False)

In [7]:
data

,timestamp,available_date,kupah,profession,doctor_name,address,days_diff,city
0,2026-07-30 13:01:20.000000,2026-08-11 00:00:00,clalit,אורתופדיה,"ד""ר הלר אייל","דרך משה דיין 147, תל אביב יפו",12.0,תל אביב יפו
1,2026-07-30 13:01:20.000000,2026-08-14 00:00:00,clalit,אורתופדיה,"ד""ר צרפתי ירון","אליהו ברלין 13, תל אביב יפו",15.0,תל אביב יפו
2,2026-07-30 13:01:20.000000,2026-08-16 00:00:00,clalit,אורתופדיה,"ד""ר אשכול זאב","אבן גבירול 124, תל אביב יפו",17.0,תל אביב יפו
3,2026-07-30 13:01:20.000000,2026-08-16 00:00:00,clalit,אורתופדיה,"ד""ר סודיה דן","שדרות ישראל גורי 39, תל אביב יפו",17.0,תל אביב יפו
4,2026-07-30 13:01:20.000000,2026-08-17 00:00:00,clalit,אורתופדיה,"ד""ר לשינר ויאצ'סלב","שדרות יד לבנים 35, תל אביב יפו",18.0,תל אביב יפו
...,...,...,...,...,...,...,...,...
3423,2026-07-31 00:42:36.208368,2026-10-04 16:00:00,maccabi,קרדיולוגיה - הפרעות קצב (אלקטרופיזיולוגיה וקוצ...,פרופ מרדכי חיים,"בן צבי יצחק 2, באר שבע",65.0,באר שבע
3424,2026-07-31 00:42:36.208368,2027-07-12 08:40:00,maccabi,ראומטולוגיה,דר ורוניק סייג-בוכריס,"התקוה 4, באר שבע",346.0,באר שבע
3425,2026-07-31 00:42:36.208368,2026-10-26 10:45:00,maccabi,ראומטולוגיה,דר מירית עמית-וזינה,"שד העצמאות 64, קריית גת",87.0,קריית גת
3426,2026-07-31 00:42:36.208368,2026-09-20 08:40:00,maccabi,רפואה שיקומית/פיזיקלית,דר סלימאן אלגרינאוי,"התקוה 4, באר שבע",51.0,באר שבע
3427,2026-07-31 00:42:36.208368,2026-10-19 17:00:00,maccabi,רפואת הפה,דר אנה פיקובסקי,"שד רגר יצחק 53/2, באר שבע",80.0,באר שבע